### ISSUE TITLE
register in QML

### ISSUE THREAD

**Issue by phaivdmta** [vplayplugins/FacebookLogin#1]
how to register file 
import VPlayPlugins.facebook 1.0

**Comment by feldifux** [comment]
Hi, you can find the integration steps here:
https://github.com/vplayplugins/FacebookLogin#user-content-instructions

**Comment by phaivdmta** [comment]
Many thanks for responding me but I have some problems.
Can you answer me requests...!
1. In file* qml/main.qml* you embedded  *import VPlayPlugins.facebook 1.0*
*but I can't see file *cpp to register (Because I always had to register a
file in Cpp before i could use it on qml file)*
*for example *qmlRegisterType<QZXing>("org.qtproject.qtquick",1 ,0 ,"QZXing"
);
2. can i add all files java at vendor folder to run your project?

2015-01-13 16:01 GMT+07:00 feldifux <notifications@github.com>:

> Closed #1 <https://github.com/vplayplugins/FacebookLogin/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vplayplugins/FacebookLogin/issues/1#event-217936176>.
>



-- 
Vũ Đình Phái
yahoo : phaivd_mta@yahoo.com
phone : 0976 818 301
LeQuyDon Technical University

**Comment by alexleutgoeb** [comment]
You actually don't need to register any items in code, as the Facebook item is already registered in the **import VPlayPlugins.facebook 1.0** namespace within our plugin.

The files in the vendor folder correspond to the official Facebook Android SDK which is needed for the plugin.

Please also consider to use our plugin support forums at https://v-play.net/developers/forums/f/v-play-plugins-support/ as we usually can't provide support here at Github.
